### PR TITLE
webpixels css for vue

### PR DESCRIPTION
**Pull request by Gavrushuk**

### CODE REVIEW

**Comment by alexisenache** [comment]
These commits are not relevant to the latest version.

**Comment by Gavrushuk** [comment]
@alexisenache Please can you check this issue https://github.com/webpixels/css/issues/2

**Comment by Gavrushuk** [comment]
@alexisenache 

> These commits are not relevant to the latest version.

What the latest version?

**Comment by jfoliveira** [comment]
Hey @alexisenache,
Thanks for the webpixels project. Looks promising!
Couldn't access the issue mentioned by @Gavrushuk 

Perhaps enabling the `issues` tab on this repo would encourage more community engagement with webpixels project, if that's something you're looking for.

**Comment by alexisenache** [comment]
Hi @jfoliveira, thanks for the feedback :)

I was going for the Discussions because I liked the idea of having the issues and the conversations contained in one place.

But I think you are right. We are still used to the issues tab, so I activated it. Now you can see the closed issue you couldn't access.

**Pull request closed without merging**
